//! Derives the active specification's identity and grammar tables at build time.
//!
//! The identity used to be a generated module committed beside the source,
//! with a test proving the committed copy matched a fresh generation. That is
//! a second copy of a fact the crate already embeds, and the test existed only
//! to police the copy: an amendment that forgot to regenerate turned the gate
//! red rather than the build. Computing it here removes the copy, the
//! regeneration step, and the test together.
//!
//! Only the two values that must exist in constant position are emitted. The
//! rule count is scanned live from the embedded text where it is used, because
//! nothing needs it before runtime and a second scanner here would reintroduce
//! exactly the duplication this removes.

use std::{env, fs, path::Path, process::Command};

#[path = "src/syntax/grammar/generator.rs"]
mod grammar_generator;

mod sha256 {
    include!("src/spec/sha256.rs");
}

const SPEC: &str = "../spec/kernel-spec.md";
const TITLE: &str = "# Kernel Specification ";

fn main() {
    println!("cargo::rerun-if-changed={SPEC}");
    println!("cargo::rerun-if-changed=src/spec/sha256.rs");
    println!("cargo::rerun-if-changed=src/syntax/grammar/generator.rs");
    println!("cargo::rerun-if-changed=src/syntax/grammar/generator/ebnf.rs");
    println!("cargo::rerun-if-changed=src/syntax/grammar/generator/model.rs");

    let bytes = fs::read(SPEC).unwrap_or_else(|error| panic!("read {SPEC}: {error}"));
    let text = std::str::from_utf8(&bytes).expect("the specification is UTF-8");
    let version = text
        .lines()
        .next()
        .and_then(|line| line.strip_prefix(TITLE))
        .unwrap_or_else(|| panic!("{SPEC} has no `{TITLE}vN` title line"));

    let mut hex = String::with_capacity(64);
    for byte in sha256::digest(&bytes) {
        hex.push_str(&format!("{byte:02x}"));
    }

    let module = format!(
        r#"// Generated by build.rs from the specification's own bytes; not committed.

/// Version token on the embedded specification's title line.
pub const SPEC_VERSION: &str = "{version}";

/// Lowercase SHA-256 hex of the embedded specification bytes.
///
/// Decoded rather than recomputed by consumers: a constant is re-evaluated in
/// every crate that reads it, and hashing the whole specification in the
/// constant evaluator costs seconds per crate. Cargo regenerates this module
/// whenever the active specification changes.
pub const SPEC_SHA256_HEX: &str = "{hex}";
"#
    );

    let out = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("spec_identity.rs");
    fs::write(&out, module).unwrap_or_else(|error| panic!("write {}: {error}", out.display()));

    let tables = grammar_generator::generate("spec/kernel-spec.md", text);
    let out = out.with_file_name("grammar_tables.rs");
    fs::write(&out, tables).unwrap_or_else(|error| panic!("write {}: {error}", out.display()));

    watch_assembler();
    println!(
        "cargo::rustc-env=WHITEFOOT_NO_CAPTURE_ATTRIBUTE={}",
        no_capture_attribute()
    );
    println!(
        "cargo::rustc-env=WHITEFOOT_PRESERVE_NONE={}",
        u8::from(preserve_none_supported())
    );
    println!(
        "cargo::rustc-env=WHITEFOOT_CORO_END_RESULT={}",
        coro_end_result()
    );
}

/// The result type of `llvm.coro.end` in the toolchain this build hands its
/// modules to (compiler/backend-facts): `i1` until LLVM changed it to
/// `void`. A module that calls the newer form is verified by the assembler
/// `whitefootc` runs, without generating code: the verifier checks the
/// intrinsic's type at a call, while some versions accept a bare declaration
/// of either form (Apple clang 21), and a call outside a coroutine can crash
/// code generation.
fn coro_end_result() -> &'static str {
    const OLD: &str = "i1";
    const NEW: &str = "void";
    let Ok(directory) = env::var("OUT_DIR") else {
        return OLD;
    };
    let probe = Path::new(&directory).join("coro_end_probe.ll");
    if fs::write(
        &probe,
        "declare void @llvm.coro.end(ptr, i1, token)\n\n\
         define void @probe() {\n  \
         call void @llvm.coro.end(ptr null, i1 false, token none)\n  ret void\n}\n",
    )
    .is_err()
    {
        return OLD;
    }
    let accepted = Command::new(assembler())
        .args(["-x", "ir", "-S", "-emit-llvm", "-o"])
        .arg(Path::new(&directory).join("coro_end_probe.verified.ll"))
        .arg(&probe)
        .output()
        .is_ok_and(|output| output.status.success());
    if accepted { NEW } else { OLD }
}

/// Whether the toolchain this build hands its modules to accepts a
/// guaranteed tail call between functions of the calling convention without
/// callee-saved registers (compiler/match-dispatch-lowering).
///
/// LLVM 19 added the convention, and no version is pinned, so it is probed:
/// a two-function module with the convention and a `musttail` call between
/// them is handed to the assembler `whitefootc` runs. Where it is refused,
/// or no assembler can be run, the lowering uses the C convention.
fn preserve_none_supported() -> bool {
    let Ok(directory) = env::var("OUT_DIR") else {
        return false;
    };
    let probe = Path::new(&directory).join("preserve_none_probe.ll");
    if fs::write(
        &probe,
        "define internal preserve_nonecc i64 @q(i64 %a) {\n  ret i64 %a\n}\n\n\
         define preserve_nonecc i64 @p(i64 %a) {\n  \
         %r = musttail call preserve_nonecc i64 @q(i64 %a)\n  ret i64 %r\n}\n",
    )
    .is_err()
    {
        return false;
    }
    Command::new(assembler())
        .args(["-x", "ir", "-c", "-o"])
        .arg(Path::new(&directory).join("preserve_none_probe.o"))
        .arg(&probe)
        .output()
        .is_ok_and(|output| output.status.success())
}

/// The assembler `whitefootc` hands its modules to (`clang_executable` in
/// src/bin/whitefootc.rs), which every probe below asks.
fn assembler() -> &'static str {
    if env::var("CARGO_CFG_TARGET_OS").is_ok_and(|os| os == "windows") {
        "clang"
    } else {
        "/usr/bin/clang"
    }
}

/// Reruns this script when the assembler changes, so the probes answer for
/// the toolchain `whitefootc` will run rather than for the one present when
/// the build directory was first made. The file named, the file a symbolic
/// link resolves to, and the `clang` in the directory the assembler reports
/// installing from are watched: macOS's `/usr/bin/clang` is a stub that an
/// update leaves untouched, while the tools it forwards to change, and
/// `DEVELOPER_DIR` can select other tools. A bare name found on `PATH`, as
/// on Windows, reruns when `PATH` changes. Switching tools with
/// `xcode-select`, which no file or variable here records, is not covered.
fn watch_assembler() {
    let assembler = assembler();
    let path = Path::new(assembler);
    if path.is_absolute() {
        println!("cargo::rerun-if-changed={assembler}");
        if let Ok(resolved) = fs::canonicalize(path)
            && resolved != path
        {
            println!("cargo::rerun-if-changed={}", resolved.display());
        }
    } else {
        println!("cargo::rerun-if-env-changed=PATH");
    }
    // macOS's stub forwards to the developer directory these select.
    println!("cargo::rerun-if-env-changed=DEVELOPER_DIR");
    let executable = if env::var("CARGO_CFG_TARGET_OS").is_ok_and(|os| os == "windows") {
        "clang.exe"
    } else {
        "clang"
    };
    if let Ok(output) = Command::new(assembler).arg("--version").output() {
        for line in String::from_utf8_lossy(&output.stdout).lines() {
            if let Some(directory) = line.strip_prefix("InstalledDir: ") {
                let installed = Path::new(directory.trim()).join(executable);
                if installed.exists() {
                    println!("cargo::rerun-if-changed={}", installed.display());
                }
            }
        }
    }
}

/// Which spelling of the no-capture parameter attribute the toolchain this
/// build will hand its modules to accepts (compiler/backend-facts).
///
/// LLVM 21 renamed `nocapture` to `captures(none)`. No version is pinned, so
/// the spelling is probed rather than assumed: a one-function module carrying
/// the new spelling is handed to the assembler, and the old spelling is used
/// when it is refused. The old spelling is also the fallback where no
/// assembler can be run at all, because every LLVM that has the new one still
/// auto-upgrades the old.
fn no_capture_attribute() -> &'static str {
    const OLD: &str = "nocapture";
    const NEW: &str = "captures(none)";
    let Ok(directory) = env::var("OUT_DIR") else {
        return OLD;
    };
    let probe = Path::new(&directory).join("captures_probe.ll");
    if fs::write(
        &probe,
        format!("define void @p(ptr {NEW} %v) {{\n  ret void\n}}\n"),
    )
    .is_err()
    {
        return OLD;
    }
    let accepted = Command::new(assembler())
        .args(["-x", "ir", "-c", "-o"])
        .arg(Path::new(&directory).join("captures_probe.o"))
        .arg(&probe)
        .output()
        .is_ok_and(|output| output.status.success());
    if accepted { NEW } else { OLD }
}
